export const AUTHENTICATED = 'AUTHENTICATED';
export const COMPLETE_REGISTRATION = 'COMPLETE_REGISTRATION';
export const LOAD_STORAGE = 'LOAD_STORAGE';
export const SETTINGS_FETCHED = 'SETTINGS_FETCHED';
