export const USER_FETCHED = 'USER_FETCHED';
export const LOAD_STORAGE = 'USER_FETLOAD_STORAGECHED';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

//USER ACCOUNT
export const USER_AUTHENTICATION_REQUEST = 'USER_AUTHENTICATION_REQUEST';
export const USER_AUTHENTICATION_SUCCESS = 'USER_AUTHENTICATION_SUCCESS';
export const USER_AUTHENTICATION_ERROR = 'USER_AUTHENTICATION_ERROR';
